# Generated by Django 4.1.6 on 2023-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=200)),
                ('shipping_method', models.CharField(default='', max_length=200)),
                ('estimated_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
            ],
        ),
    ]
