# Generated by Django 4.1.6 on 2023-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('payment_done_date', models.DateTimeField()),
            ],
        ),
    ]
