# Generated by Django 4.1.6 on 2023-04-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='lname',
        ),
    ]
