# Generated by Django 4.1.6 on 2023-04-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0002_remove_cart_fname_remove_cart_lname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='carts',
        ),
    ]
