# Generated by Django 4.1.6 on 2023-04-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0003_rename_cart_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
