# Generated by Django 4.1.6 on 2023-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0004_carts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
