# Generated by Django 4.1.6 on 2023-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0005_alter_carts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
