# Generated by Django 4.1.6 on 2023-05-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0006_alter_carts_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='email',
        ),
        migrations.AddField(
            model_name='carts',
            name='customerid',
            field=models.IntegerField(default=0),
        ),
    ]
